config/routes.rb
Rails.application.routes.draw do
  
  get 'leaderboard/index'

  resources :bookitems
  resources :users
  resources :users2books
  resources :dualbooklists
  resources :rewards
  resources :goals
  resources :users2rewards
  resources :users2goals
  

  root 'welcome#index'
  get "app/views/welcome/masterview", to: "welcome#masterview", as: "masterview"
  get "app/views/welcome/contact", to: "welcome#contact", as: "contact"
  get "app/views/welcome/careers", to: "welcome#careers", as: "careers"
  get "app/views/welcome/about", to: "welcome#about", as: "about"

  get "app/views/welcome/displayview", to: "welcome#displayview", as: "displayview"
  get "app/views/welcome/infoview", to: "welcome#infoview", as: "infoview"

  get "app/views/welcome/classsummary", to: "welcome#classsummary", as: "classsummary"

  get "app/views/welcome/matching", to:"welcome#matching", as: "matching"
  post "app/views/welcome/displayscores", to:"welcome#displayscores", as: "displayscores"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookitem.rb
class Bookitem < ApplicationRecord
  validates_presence_of :title, :author
  validates_uniqueness_of :title
  validates_numericality_of :pages,
    :message => "Should be numeric value."
  #belongs_to :users2book
end

app/models/dualbooklist.rb
class Dualbooklist < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/models/reward.rb
class Reward < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  #has_many :users2book
end

app/models/users2book.rb
class Users2book < ApplicationRecord
  #belongs_to :User
  #has_many :bookitem
end

app/models/users2goal.rb
class Users2goal < ApplicationRecord
end

app/models/users2reward.rb
class Users2reward < ApplicationRecord
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@goals = Goal.all
	end


	def show 
		@goal = Goal.find(params[:id])
	end


	def new
		@goal = Goal.new
	end


	def edit
		@goal = Goal.find(params[:id])		
	end


	def create
		@goal = Goal.new(goal_params)

		if @goal.save

			if false
				redirect_to @goal
			end
			redirect_to goals_path
		else
			render 'new'
		end
	end


	def update
  		@goal = Goal.find(params[:id])

  		if @goal.update(goal_params)
  			redirect_to @goal
  		else
  			render 'edit'
  		end
 

	end
	

	def destroy
		@goal = Goal.find(params[:id])
		@goal.destroy

		redirect_to goals_path
	end


	private
	def goal_params
		params.require(:goal).permit(:name,:text,:is_class)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@users = User.all
	end


	def show

		@users2books = Users2book.all
		@bookitems = Bookitem.all

		@user = User.find(params[:id])
		@newUserBook = Users2book.new

		@page_sum = 0
		@books_total = 0
			@booklist = Users2book.all.each do |user2book|
				if user2book.userid === @user.id
				 @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages
				 @books_total = @books_total + 1
				end
			end
		@user.pages_read = @page_sum
		@user.books_read = @books_total

		#this will implement the users reading level based on # of pages and books read
		@standing = ""
		if @user.pages_read >= 0 && @user.books_read >= 0
			@standing = "Novice"
		end
		if @user.pages_read > 200 && @user.books_read > 3
			@standing = "Apprentice"
		end
		if @user.pages_read > 1000 && @user.books_read > 10
			@standing = "Journey Man"
		end
		if @user.pages_read > 10000 && @user.books_read > 20
			@standing = "Master"
		end
		@user.reading_level = @standing
		@user.save
	end



	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
		@page_sum = 0
		@books_total = 0
			@booklist = Users2book.all.each do |user2book|
				if user2book.userid === @user.id
				 @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages
				 @books_total = @books_total + 1
				end
			end
		@user.pages_read = @page_sum
		@user.books_read = @books_total

		#this will implement the users reading level based on # of pages and books read
		@standing = ""
		if @user.pages_read >= 0 && @user.books_read >= 0
			@standing = "Novice"
		end
		if @user.pages_read > 200 && @user.books_read > 3
			@standing = "Apprentice"
		end
		if @user.pages_read > 1000 && @user.books_read > 10
			@standing = "Journey Man"
		end
		if @user.pages_read > 10000 && @user.books_read > 20
			@standing = "Master"
		end


		@user.reading_level = @standing
		@user.save

	end


	def create

		@user = User.new(user_params)

		@user.pages_read = 0
		@user.books_read = 0

		@user.reading_level = "Novice"

		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end


	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end


private
	def user_params
		params.require(:user).permit(:name, :is_teacher, :age, :pages_read, :books_read, :reading_level, :book_list)

	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def masterview
    @users = User.all
  	@bookitems = Bookitem.all
  	@users2books = Users2book.all
  end

  def contact

  end

  def careers

  end

  def about
  	
  end
  
  def classsummary
	@numstudents = User.where("is_teacher = 'false'").count
	@studentslist = User.where("is_teacher = 'false'").first(@numstudents)
	
	@studentsquery = User.where("is_teacher = 'false'")
	
	#number of pages read by all students in class.
	@classpagetotal = 0
	@allbooklists = Users2book.all
	for @bookread in @allbooklists
		@curbookspages = Bookitem.find(@bookread.bookid).pages
		@classpagetotal = @classpagetotal + @curbookspages
	end
	#number of nonunique books read by all students in class.
	@nonuniquebooksread = Users2book.all.count
	
	#average age
	@averageage = @studentsquery.average("age").round(1)
	
	#top 3 students
	@topthreestudents = User.all.order(pages_read: :desc).first(3)
	
	#bottom 3 students
	@bottomthreestudents = User.all.order(pages_read: :asc).first(3).reverse
	
	#highest pages read
	@highestpagesread = User.all.order(pages_read: :desc).first().pages_read
	
	#lowest pages read
	@fewestpagesread = User.all.order(pages_read: :asc).first().pages_read
	
  end

  def displayview

    @user_options = User.all.map{ |u| [ u.name, u.id ] }
    @users = User.all
    @bookitems = Bookitem.all
    @users2books = Users2book.all
  end

  def infoview
    Rails.logger.debug(:user_id)
    Rails.logger.debug(:foo_param)
    @foo = params[:foo_param] #maybe?
   

  end
	
	def matching
		
	end
	
	def displayscores
	
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookitems_helper.rb
module BookitemsHelper
end

app/helpers/dualbooklists_helper.rb
module DualbooklistsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/users2books_helper.rb
module Users2booksHelper
end

app/helpers/users2goals_helper.rb
module Users2goalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
Brigham

Tyson

Krista

Bridget

app/views/welcome/careers.html.erb
Yes we all want careers in computer science and we also want morbidly obese bank accounts!

app/views/welcome/classsummary.html.erb
<h1>Summary of your class:</h1>
<p>Number of students in class: <%= @numstudents %></p>
<p>Total pages read by class: <%= @classpagetotal %></p>
<p>Total nonunique books read: <%= @nonuniquebooksread %></p>
<p>Highest pages read: <%= @highestpagesread %></p>
<p>Fewest pages read: <%= @fewestpagesread %></p>
<p>Average age in class: <%= @averageage %></p>
<table>
	<tr>
		<th>Top Three Students</th>
	</tr>
	<tr>
		<th>Name</th>
		<th>Pages Read</th>
	</tr>
<% for @student in @topthreestudents %>
	<tr>
		<td><%= @student.name %></td>
		<td><%= @student.pages_read %></td>
	</tr>
<% end %>
</table>
<br>
<table>
	<tr>
		<th>Bottom Three Students</th>
	</tr>
	<tr>
		<th>Name</th>
		<th>Pages Read</th>
	</tr>
<% for @student in @bottomthreestudents %>
	<tr>
		<td><%= @student.name %></td>
		<td><%= @student.pages_read %></td>
	</tr>
<% end %>
</table>
<br>
<table>
	<tr>
		<th>All Students in Class</th>
	</tr>
<% for @student in @studentslist %>
	<tr>
		<td><%= @student.name %></td>
	</tr>
<% end %>
</table>

app/views/welcome/contact.html.erb
No you may not contact us!

This software is "Use at your own risk!"

app/views/welcome/displayscores.html.erb
<h1>Leader Rankings</h1>
<form action='/' method="get">
    <input type="submit" value="Start a new game!">
</form>
<table>
    <% blogs.forEach(function(unit){ %>
    <tr><td>______________________________________________________________________________</td></tr>
    <tr><td> First Name: <%= unit.fname %></td></tr>
    <tr><td> Last Name : <%= unit.lname %></td></tr>
    <tr><td> DATE CREATED: <%= unit.created %></td></tr>
    <tr><td> SCORE: <%= unit.score %></td></tr>
    <td><a href='/QuizGame/<%= unit.id %>?_method=DELETE' >Delete</a></td>
    </tr>
    <% }) %>
</table>

app/views/welcome/displayview.html.erb
hello to the display


<h1>The complete listing of the people base!</h1>
<%= link_to 'HOME', controller: 'welcome' %>
 <%= link_to 'New User', new_user_path %>
<table>
  <tr>
    <th>Name</th>
    <th>ID</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.id %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),method: :delete,data: { confirm: 'Are you Sure?' } %> </td>
    </tr>
  <% end %>
</table>









<% 
=begin %> 


<%= select("person", "role_id", @users.collect {|r| [ r.name, r.id ] }, { :include_blank => true } ) %>

<%= select("person", "role_id", User.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'None'})  %>

<%= select("person", "role_id", @users.collect {|r| [ r.name, r.id ] },,{ :include_blank => false } ) %>

<%= select_tag(:author_id, options_for_select(@user_options)) %>
<%= select(:user, :author_id, @user_options) %>



<%= select_tag(:author_id, options_for_select(@user_options)) %>


     <select name="user_id">
      <%= @users.each do |user| %>
        <option value="<%= user.id %>"><%= user.name %></option>
      <% end %>
    </select>




<% 
=end %>



<%= collection_select(@lang_id, 0, User.all, :id, :name) %>


<% @firstp = 3 %>
########################

<%= link_to "Connect", infoview_path(foo_param: @lang_id) %>

app/views/welcome/index.html.erb
<h1>Welcome to the Readathon Homepage!</h1>
<%= link_to 'THE PEOPLE BASE', controller: 'users' %>
<%= link_to 'THE BOOK LIST', controller: 'bookitems' %>
<%= link_to 'THE Reward List', controller: 'rewards' %>
<%= link_to 'THE Goal List', controller: 'goals' %>

<%= link_to 'GIVE SOMEONE A Reward', controller: 'users2rewards'%>
<%= link_to 'GIVE SOMEONE A Goal', controller: 'users2goals'%>
<%= link_to 'GIVE SOMEONE A BOOK TO READ', controller: 'users2books'%>
<%= link_to 'DUAL!', controller: 'dualbooklists'%>



<h3><strong><%= link_to 'DisplayView', displayview_path %></strong></h3>



<%= link_to 'LEADERBOARD', controller: 'leaderboard', action: 'index' %>
<%= link_to 'CLASS SUMMARY', controller: 'welcome', action: 'classsummary' %>

<%= link_to 'Reading Quiz', controller: 'welcome', action: 'matching' %>

app/views/welcome/infoview.html.erb
hello
<pre>

	<%= @foo.inspect%>
	
</pre>

<% if @foo.to_i == 1 %>
<%= "inside"%>
<% else %>
<%= "notinside" %>

<% end %>

app/views/welcome/masterview.html.erb
<h1>The complete listing of the people base!</h1>
<%= link_to 'HOME', controller: 'welcome' %>
 <%= link_to 'New User', new_user_path %>
<table>
  <tr>
    <th>Name</th>
    <th>ID</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.id %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),method: :delete,data: { confirm: 'Are you Sure?' } %> </td>
    </tr>
  <% end %>
</table>



<h1>Listing all the books of superior Knowledge</h1>

<%= link_to 'HOME', controller: 'welcome' %>
<%= link_to 'new Book', new_bookitem_path %>

<table>
  <tr>
    <th>Title</th>
    <th>ID</th>
  </tr>
 
  <% @bookitems.each do |bookitem| %>
    <tr>
      <td><%= bookitem.title %></td>
      <td><%= bookitem.id %></td>
      <td><%= link_to 'Show', bookitem_path(bookitem) %></td>
      <td><%= link_to 'Edit', edit_bookitem_path(bookitem) %></td>
      <td><%= link_to 'Destroy', bookitem_path(bookitem), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>



<h1>Listing all the things</h1>

<%= link_to 'HOME', controller: 'welcome' %>
<%= link_to 'new thing', new_users2book_path %>

<table>
  <tr>
    <th>UserID</th>
    <th>BookID</th>
  </tr>
 
  <% @users2books.each do |users2book| %>
    <tr>
      <td><%= users2book.userid %></td>
      <td><%= users2book.bookid %></td>
      <td><%= link_to 'Show', users2book_path(users2book) %></td>
      <td><%= link_to 'Edit', edit_users2book_path(users2book) %></td>
      <td><%= link_to 'Destroy', users2book_path(users2book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/matching.html.erb
<h1>WELCOME TO THE GAME</h1>

<h3>This is a quiz game</h3>
</br>
Just hit "Finish the Game" When you are ready to quit.
<div id="question">
    <h3 id="current-question"></h3>
    <p id="first-q"></p><input type="radio" name="answer" value="correct">
    <p id="second-q"></p><input type="radio" name="answer" value="incorrect"></br></br>
    <button type="button" >submit answer</button>
</div>



<%= link_to 'Finish the Game', controller: 'welcome', action: 'index' %>
<form>
    <input type="hidden" name="score" value="5" id="scorekeeper">
</form>