config/routes.rb
Rails.application.routes.draw do
  
  get 'leaderboard/index'

  resources :bookitems
  resources :users
  resources :users2books
  resources :dualbooklists
  resources :rewards
  resources :goals
  resources :users2rewards
  resources :users2goals
  

  root 'welcome#index'
  get "app/views/welcome/masterview", to: "welcome#masterview", as: "masterview"
  get "app/views/welcome/contact", to: "welcome#contact", as: "contact"
  get "app/views/welcome/careers", to: "welcome#careers", as: "careers"
  get "app/views/welcome/about", to: "welcome#about", as: "about"

  get "app/views/welcome/displayview", to: "welcome#displayview", as: "displayview"
  get "app/views/welcome/infoview", to: "welcome#infoview", as: "infoview"

  get "app/views/welcome/classsummary", to: "welcome#classsummary", as: "classsummary"

  get "app/views/welcome/matching", to:"welcome#matching", as: "matching"
  post "app/views/welcome/displayscores", to:"welcome#displayscores", as: "displayscores"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookitem.rb
class Bookitem < ApplicationRecord
  validates_presence_of :title, :author
  validates_uniqueness_of :title
  validates_numericality_of :pages,
    :message => "Should be numeric value."
  #belongs_to :users2book
end

app/models/dualbooklist.rb
class Dualbooklist < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/models/reward.rb
class Reward < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  #has_many :users2book
end

app/models/users2book.rb
class Users2book < ApplicationRecord
  #belongs_to :User
  #has_many :bookitem
end

app/models/users2goal.rb
class Users2goal < ApplicationRecord
end

app/models/users2reward.rb
class Users2reward < ApplicationRecord
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@goals = Goal.all
	end


	def show 
		@goal = Goal.find(params[:id])
	end


	def new
		@goal = Goal.new
	end


	def edit
		@goal = Goal.find(params[:id])		
	end


	def create
		@goal = Goal.new(goal_params)

		if @goal.save

			if false
				redirect_to @goal
			end
			redirect_to goals_path
		else
			render 'new'
		end
	end


	def update
  		@goal = Goal.find(params[:id])

  		if @goal.update(goal_params)
  			redirect_to @goal
  		else
  			render 'edit'
  		end
 

	end
	

	def destroy
		@goal = Goal.find(params[:id])
		@goal.destroy

		redirect_to goals_path
	end


	private
	def goal_params
		params.require(:goal).permit(:name,:text,:is_class)
	end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@rewards = Reward.all
	end


	def show 
		@reward = Reward.find(params[:id])
	end


	def new
		@reward = Reward.new
	end


	def edit
		@reward = Reward.find(params[:id])
	end


	def create
		@reward = Reward.new(reward_params)

		if @reward.save
			
			if false
				redirect_to @reward
			end
			redirect_to rewards_path
		else
			render 'new'
		end
	end


	def update
		@reward = Reward.find(params[:id])

		if @reward.update(reward_params)
			redirect_to @reward
		else
			render 'edit'
		end
	end


	def destroy
		@reward = Reward.find(params[:id])
		@reward.destroy

		redirect_to rewards_path
	end


	private
	def reward_params
		params.require(:reward).permit(:name,:text,:is_class)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@users = User.all
	end


	def show

		@users2books = Users2book.all
		@bookitems = Bookitem.all

		@user = User.find(params[:id])
		@newUserBook = Users2book.new

		@page_sum = 0
		@books_total = 0
			@booklist = Users2book.all.each do |user2book|
				if user2book.userid === @user.id
				 @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages
				 @books_total = @books_total + 1
				end
			end
		@user.pages_read = @page_sum
		@user.books_read = @books_total

		#this will implement the users reading level based on # of pages and books read
		@standing = ""
		if @user.pages_read >= 0 && @user.books_read >= 0
			@standing = "Novice"
		end
		if @user.pages_read > 200 && @user.books_read > 3
			@standing = "Apprentice"
		end
		if @user.pages_read > 1000 && @user.books_read > 10
			@standing = "Journey Man"
		end
		if @user.pages_read > 10000 && @user.books_read > 20
			@standing = "Master"
		end
		@user.reading_level = @standing
		@user.save
	end



	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
		@page_sum = 0
		@books_total = 0
			@booklist = Users2book.all.each do |user2book|
				if user2book.userid === @user.id
				 @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages
				 @books_total = @books_total + 1
				end
			end
		@user.pages_read = @page_sum
		@user.books_read = @books_total

		#this will implement the users reading level based on # of pages and books read
		@standing = ""
		if @user.pages_read >= 0 && @user.books_read >= 0
			@standing = "Novice"
		end
		if @user.pages_read > 200 && @user.books_read > 3
			@standing = "Apprentice"
		end
		if @user.pages_read > 1000 && @user.books_read > 10
			@standing = "Journey Man"
		end
		if @user.pages_read > 10000 && @user.books_read > 20
			@standing = "Master"
		end


		@user.reading_level = @standing
		@user.save

	end


	def create

		@user = User.new(user_params)

		@user.pages_read = 0
		@user.books_read = 0

		@user.reading_level = "Novice"

		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end


	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end


private
	def user_params
		params.require(:user).permit(:name, :is_teacher, :age, :pages_read, :books_read, :reading_level, :book_list)

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookitems_helper.rb
module BookitemsHelper
end

app/helpers/dualbooklists_helper.rb
module DualbooklistsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/users2books_helper.rb
module Users2booksHelper
end

app/helpers/users2goals_helper.rb
module Users2goalsHelper
end

app/helpers/users2rewards_helper.rb
module Users2rewardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/goals/edit.html.erb
<h1>Editing a Goal</h1>

<%= form_for :goal, url: goal_path(@goal), method: :patch do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>

  </p>


  <p>
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </p>

   <p>
    <div>
      <%= f.label :is_class, "Class Room Goal", :value => true %>
      <%= f.radio_button :is_class, true %>
    </div>

    <div>
      <%= f.label :is_class, "Individual Goal", :value => false %>
      <%= f.radio_button :is_class, false %>
    </div>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<h1>Listing all the goals</h1>

<%= link_to 'HOME', controller: 'welcome' %>
<%= link_to 'Create a new goal', new_goal_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Info</th>
    <th>bool</th>
    <th>id</th>
  </tr>
 
  <% @goals.each do |goal| %>
    <tr>
      <td><%= goal.name %></td>
      <td><%= goal.text %></td>
      <td><%= goal.is_class %></td>
      <td><%= goal.id %></td>
      <td><%= link_to 'Show', goal_path(goal) %></td>
      <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
      <td><%= link_to 'Destroy', goal_path(goal), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/goals/new.html.erb
<h1>Please add a new Goal!</h1>

<%= form_for :goal, url: goals_path do |f| %>

 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>

  </p>


  <p>
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </p>

   <p>
    <div>
      <%= f.label :is_class, "Class Room Goal", :value => true %>
      <%= f.radio_button :is_class, true %>
    </div>

    <div>
      <%= f.label :is_class, "Individual Goal", :value => false %>
      <%= f.radio_button :is_class, false %>
    </div>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @goal.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @goal.text %>
</p>

<p>
  <strong>bool:</strong>
  <%= @goal.is_class %>
</p>
 
 <%= link_to 'Back', goals_path %>

app/views/rewards/edit.html.erb
<h1>Editing a Reward</h1>

<%= form_for :reward, url: reward_path(@reward), method: :patch do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>

  </p>


  <p>
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </p>

   <p>
    <div>
      <%= f.label :is_class, "Class Room Goal", :value => true %>
      <%= f.radio_button :is_class, true %>
    </div>

    <div>
      <%= f.label :is_class, "Individual Goal", :value => false %>
      <%= f.radio_button :is_class, false %>
    </div>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<h1>Listing all the Rewards </h1>

<%= link_to 'HOME', controller: 'welcome' %>
<%= link_to 'Create a New reward', new_reward_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Info</th>
    <th>bool</th>
    <th>id</th>
  </tr>
 
  <% @rewards.each do |reward| %>
    <tr>
      <td><%= reward.name %></td>
      <td><%= reward.text %></td>
      <td><%= reward.is_class %></td>
      <td><%= reward.id %></td>
      <td><%= link_to 'Show', reward_path(reward) %></td>
      <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
      <td><%= link_to 'Destroy', reward_path(reward), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/rewards/new.html.erb
<h1>Please add a new Reward!</h1>

<%= form_for :reward, url: rewards_path do |f| %>


  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>

  </p>


  <p>
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </p>

   <p>
    <div>
      <%= f.label :is_class, "Class Room Goal", :value => true %>
      <%= f.radio_button :is_class, true %>
    </div>

    <div>
      <%= f.label :is_class, "Individual Goal", :value => false %>
      <%= f.radio_button :is_class, false %>
    </div>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @reward.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @reward.text %>
</p>

<p>
  <strong>bool:</strong>
  <%= @reward.is_class %>
</p>
 
 <%= link_to 'Back', rewards_path %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<%= form_for :user, url: user_path(@user), method: :patch do |f| %>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %> <br>
  <% end %>
<% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <div>
      <%= f.label :is_teacher, "Teacher", :value => true %>
      <%= f.radio_button :is_teacher, true %>
    </div>

    <div>
      <%= f.label :is_teacher, "Student", :value => false %>
      <%= f.radio_button :is_teacher, false %>
    </div>
  </p>

  <p>
  	<strong>Book list: </strong>
  	<% @booklist = Users2book.all.each do |user2book| %>
  		<% if user2book.userid === @user.id %>
  			<p> <%= Bookitem.find_by_id(user2book.bookid).title %> </p>
  		<% end %>
  	<% end %>
  </p>
<br>

<% @page_sum = 0 %>
  <% @booklist = Users2book.all.each do |user2book| %>
  	<% if user2book.userid === @user.id %>
  	 <% @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages %>
  	<% end %>
  <% end %>

  <p>
    <%= f.submit %>
  </p>


<% end %>
 <%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>The complete listing of the people base!</h1>
<%= link_to 'HOME', controller: 'welcome' %>
 <%= link_to 'New User', new_user_path %>
<table>
  <tr>
    <th>Name: </th>
    <th>Status: </th>
    <th>Pages Read: </th>
    <th>Books Read: </th>
    <th>Reading Level:</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td>
        <% if user.is_teacher %>
        <%= "Teacher" %>
        <% else %>
        <%= "Student" %>
        <% end %>
      </td>
      <td><%= user.pages_read %></td>
      <td><%= user.books_read %></td>
      <td><%= user.reading_level %></td>
      <td><%= link_to 'Stats', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),method: :delete,data: { confirm: 'Are you Sure?' } %> </td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Add a new User to the people base! </h1>

<%= form_for :user, url: users_path do |f| %>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %> <br>
  <% end %>
<% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <div>
      <%= f.label :is_teacher, "Teacher", :value => true %>
      <%= f.radio_button :is_teacher, true %>
    </div>

    <div>
      <%= f.label :is_teacher, "Student", :value => false %>
      <%= f.radio_button :is_teacher, false %>
    </div>
  </p>

  <p>
    <%= f.label :book_list %><br>
    Add field here to add book IDs to this user...
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><center><strong>Student Stats</strong></center> </h1>
<p>
<strong> <font size = "+2"><%= @user.name %></font></strong>
</p>

<p>
	    <% if @user.is_teacher %>
        <%= "Teacher" %>
        <% else %>
        <%= "Student" %>
        <% end %>
</p>

<p>
	<strong>Total Pages Read: </strong>
	<%= @user.pages_read %>
</p>

<p>
	<strong>Total Books Read: </strong>
	<%= @user.books_read %>
</p>

<p>
	<strong>Reading Level: </strong>
	<%= @user.reading_level %>
</p>

<p>
	<strong >Book list: </strong>
	<% @booklist = Users2book.all.each do |user2book| %>
		<% if user2book.userid === @user.id %>
			<p> <%= Bookitem.find_by_id(user2book.bookid).title %> </p>
		<% end %>
	<% end %>
</p>


<%= form_for :users2book, url: users2books_path do |f| %>

  <p>
    <%= f.hidden_field :userid, :value=> @user.id %>
  </p>

  <h2>GIVE ME A BOOK TO READ!!!</h2>
  <p>
    <%= f.collection_select :bookid, @bookitems, :id, :title, include_blank: false %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>





<%= link_to 'Back', users_path %>