config/routes.rb
Rails.application.routes.draw do
  
  get 'leaderboard/index'

  resources :bookitems
  resources :users
  resources :users2books
  resources :dualbooklists
  resources :rewards
  resources :goals
  resources :users2rewards
  resources :users2goals
  

  root 'welcome#index'
  get "app/views/welcome/masterview", to: "welcome#masterview", as: "masterview"
  get "app/views/welcome/contact", to: "welcome#contact", as: "contact"
  get "app/views/welcome/careers", to: "welcome#careers", as: "careers"
  get "app/views/welcome/about", to: "welcome#about", as: "about"

  get "app/views/welcome/displayview", to: "welcome#displayview", as: "displayview"
  get "app/views/welcome/infoview", to: "welcome#infoview", as: "infoview"

  get "app/views/welcome/classsummary", to: "welcome#classsummary", as: "classsummary"

  get "app/views/welcome/matching", to:"welcome#matching", as: "matching"
  post "app/views/welcome/displayscores", to:"welcome#displayscores", as: "displayscores"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookitem.rb
class Bookitem < ApplicationRecord
  validates_presence_of :title, :author
  validates_uniqueness_of :title
  validates_numericality_of :pages,
    :message => "Should be numeric value."
  #belongs_to :users2book
end

app/models/dualbooklist.rb
class Dualbooklist < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/models/reward.rb
class Reward < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  #has_many :users2book
end

app/models/users2book.rb
class Users2book < ApplicationRecord
  #belongs_to :User
  #has_many :bookitem
end

app/models/users2goal.rb
class Users2goal < ApplicationRecord
end

app/models/users2reward.rb
class Users2reward < ApplicationRecord
end

app/controllers/dualbooklists_controller.rb
class DualbooklistsController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@users2books = Users2book.all
		@users = User.all
		@bookitems = Bookitem.all
		@dualbooklists = Dualbooklist.all

	end


	def show

		@users = User.all
		@bookitems = Bookitem.all
		@users2books = Users2book.all
		@dualbooklist = Dualbooklist.find(params[:id])


	end



	def new

		@users = User.all
		@bookitems = Bookitem.all
		@users2books = Users2book.all
		@dualbooklist = Dualbooklist.new
	end

	def edit

		@users = User.all
		@bookitems = Bookitem.all
		@users2books = Users2book.all

		@dualbooklist = Dualbooklist.find(params[:id])
	end


	def create

		@users = User.all
		@bookitems = Bookitem.all
		@users2books = Users2book.all
		
		@dualbooklist = Dualbooklist.new(dualbooklist_params)

		if @dualbooklist.save
			redirect_to @dualbooklist
		else
			render 'new'
		end
	end

	def update

		@users = User.all
		@bookitems = Bookitem.all

		@dualbooklist = Dualbooklist.find(params[:id])
		if @dualbooklist.update(dualbooklist_params)
			redirect_to @dualbooklist
		else
			render 'edit'
		end
	end


	def destroy
		@dualbooklist = Dualbooklist.find(params[:id])
		@dualbooklist.destroy

		redirect_to dualbooklists_path
	end


private 
	def dualbooklist_params
		params.require(:dualbooklist).permit(:studentone,:studenttwo)
		
	end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@goals = Goal.all
	end


	def show 
		@goal = Goal.find(params[:id])
	end


	def new
		@goal = Goal.new
	end


	def edit
		@goal = Goal.find(params[:id])		
	end


	def create
		@goal = Goal.new(goal_params)

		if @goal.save

			if false
				redirect_to @goal
			end
			redirect_to goals_path
		else
			render 'new'
		end
	end


	def update
  		@goal = Goal.find(params[:id])

  		if @goal.update(goal_params)
  			redirect_to @goal
  		else
  			render 'edit'
  		end
 

	end
	

	def destroy
		@goal = Goal.find(params[:id])
		@goal.destroy

		redirect_to goals_path
	end


	private
	def goal_params
		params.require(:goal).permit(:name,:text,:is_class)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@users = User.all
	end


	def show

		@users2books = Users2book.all
		@bookitems = Bookitem.all

		@user = User.find(params[:id])
		@newUserBook = Users2book.new

		@page_sum = 0
		@books_total = 0
			@booklist = Users2book.all.each do |user2book|
				if user2book.userid === @user.id
				 @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages
				 @books_total = @books_total + 1
				end
			end
		@user.pages_read = @page_sum
		@user.books_read = @books_total

		#this will implement the users reading level based on # of pages and books read
		@standing = ""
		if @user.pages_read >= 0 && @user.books_read >= 0
			@standing = "Novice"
		end
		if @user.pages_read > 200 && @user.books_read > 3
			@standing = "Apprentice"
		end
		if @user.pages_read > 1000 && @user.books_read > 10
			@standing = "Journey Man"
		end
		if @user.pages_read > 10000 && @user.books_read > 20
			@standing = "Master"
		end
		@user.reading_level = @standing
		@user.save
	end



	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
		@page_sum = 0
		@books_total = 0
			@booklist = Users2book.all.each do |user2book|
				if user2book.userid === @user.id
				 @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages
				 @books_total = @books_total + 1
				end
			end
		@user.pages_read = @page_sum
		@user.books_read = @books_total

		#this will implement the users reading level based on # of pages and books read
		@standing = ""
		if @user.pages_read >= 0 && @user.books_read >= 0
			@standing = "Novice"
		end
		if @user.pages_read > 200 && @user.books_read > 3
			@standing = "Apprentice"
		end
		if @user.pages_read > 1000 && @user.books_read > 10
			@standing = "Journey Man"
		end
		if @user.pages_read > 10000 && @user.books_read > 20
			@standing = "Master"
		end


		@user.reading_level = @standing
		@user.save

	end


	def create

		@user = User.new(user_params)

		@user.pages_read = 0
		@user.books_read = 0

		@user.reading_level = "Novice"

		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end


	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end


private
	def user_params
		params.require(:user).permit(:name, :is_teacher, :age, :pages_read, :books_read, :reading_level, :book_list)

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookitems_helper.rb
module BookitemsHelper
end

app/helpers/dualbooklists_helper.rb
module DualbooklistsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/users2books_helper.rb
module Users2booksHelper
end

app/helpers/users2goals_helper.rb
module Users2goalsHelper
end

app/helpers/users2rewards_helper.rb
module Users2rewardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dualbooklists/edit.html.erb
<h1>BOOKLIST VS. BOOKLIST CHALLENGE</h1>
 
<%= form_for :dualbooklist, url: dualbooklist_path(@dualbooklist), method: :patch do |f| %>



  <h2>Please Choose your name: </h2>
  <p>
    <%= f.collection_select :studentone, @users, :id, :name, include_blank: false %>
  </p>
 
  <h2>Please Choose the name of the Challenger: </h2>
  <p>
	<%= f.collection_select :studenttwo, @users, :id, :name, include_blank: false %>
  </p>

 
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', dualbooklists_path %>

app/views/dualbooklists/index.html.erb
<h1>LET'S DUEL!!!!!</h1>

<%= link_to 'Back ', controller: 'welcome' %>
<%#= link_to 'new thing', new_dualbooklist_path %>

<table>
  <tr>

  </tr>

  <% @dualbooklists.each do |dualbooklist| %>
    <tr>
      <td><%#= dualbooklist.studentone %></td>
      <td><%#= dualbooklist.studenttwo %></td>
      <td><%#= link_to 'Show', dualbooklist_path(dualbooklist) %></td>
      <td><%= link_to 'Begin a Booklist DUEL!!!', edit_dualbooklist_path(dualbooklist) %></td>
      <td><%#= link_to 'Destroy', dualbooklist_path(dualbooklist), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/dualbooklists/new.html.erb
<h1>Please add a new user to book</h1>

<%= form_for :dualbooklist, url: dualbooklists_path do |f| %>


<table>
  <tr>
    <th>Name</th>
    <th>ID</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.id %></td>
    </tr>
  <% end %>
</table>


  <h2>Please enter the user ID for student one:</h2>
  <p>
    <%= f.label :studentone %><br>
    <%= f.text_field :studentone %>
  </p>
 
  <h2>Please enter the user ID for student two:</h2>
  <p>
    <%= f.label :studenttwo %><br>
    <%= f.text_field :studenttwo %>
  </p>

 
 
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', dualbooklists_path %>

app/views/dualbooklists/show.html.erb
<h1 align="center"><strong>WHO HAS THE BETTER BOOKLIST?!!!</strong></h1>

<style type="text/css">
#wrap {
   width:600px;
   margin:0 auto;
}
#left_col {
   float:left;
   width:300px;
   background: rgba(102, 136, 102, 0.48);
   height: 500px;
   l
}
#right_col {
   float:right;
   width:300px;
   background: #668866;
   height: 500px;
}
</style>

<div id="wrap">
    <div id="left_col">
        <p>
          <% @chal1 = User.all.each do |c1| %>
            <% if c1.id === @dualbooklist.studentone %>
              <p><strong> <font size = "+2"><%= User.find_by_id(c1.id).name %> </strong></font></p>
            <% end %>
          <% end %>
        </p>

       <p>
      	<strong> And the Book List: </strong>
        <% @page_sum = 0 %>
        <% @book_total = 0 %>
      	<% @booklist = Users2book.all.each do |user2book| %>
      		<% if user2book.userid === @dualbooklist.studentone %>
      			<p> <%= Bookitem.find_by_id(user2book.bookid).title %> </p>
            <% @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages %>
            <% @book_total = @book_total + 1 %>
      		<% end %>
      	<% end %>
        <p style="position: absolute; bottom: 0"><strong> Total Pages: </strong><%= @page_sum %></p>
        <p style="position: absolute; bottom: -24px"><strong> Total Books: </strong><%= @book_total %></p>
        <p style="position: absolute; bottom: -47px"><strong> Pages per Book: </strong><%= @page_sum / @book_total %></p>

      </p>

  </div>
  <div id="right_col">
      <p>
        <% @chal2 = User.all.each do |c2| %>
          <% if c2.id === @dualbooklist.studenttwo %>
            <p><strong><font size = "+2"><%= User.find_by_id(c2.id).name %></strong></font> </p>
          <% end %>
        <% end %>
      </p>
      <p>
        <% @page_sum2 = 0 %>
        <% @book_total2 = 0 %>
        <strong> And the Book List: </strong>
      	<% @booklist = Users2book.all.each do |user2book| %>
      		<% if user2book.userid === @dualbooklist.studenttwo %>
      			<p> <%= Bookitem.find_by_id(user2book.bookid).title %> </p>
            <% @page_sum2 = @page_sum2 + Bookitem.find_by_id(user2book.bookid).pages %>
            <% @book_total2 = @book_total2 + 1 %>
      		<% end %>
      	<% end %>
        <p style="position: absolute; bottom: 0"><strong> Total Pages: </strong><%= @page_sum2 %></p>
        <p style="position: absolute; bottom: -24px"><strong> Total Books: </strong><%= @book_total2 %></p>
        <p style="position: absolute; bottom: -47px"><strong> Pages per Book: </strong><%= @page_sum2 / @book_total2 %></p>

      </p>
  </div>
</div>








 <%= link_to 'Back', dualbooklists_path %>