config/routes.rb
Rails.application.routes.draw do
  
  get 'leaderboard/index'

  resources :bookitems
  resources :users
  resources :users2books
  resources :dualbooklists
  resources :rewards
  resources :goals
  resources :users2rewards
  resources :users2goals
  

  root 'welcome#index'
  get "app/views/welcome/masterview", to: "welcome#masterview", as: "masterview"
  get "app/views/welcome/contact", to: "welcome#contact", as: "contact"
  get "app/views/welcome/careers", to: "welcome#careers", as: "careers"
  get "app/views/welcome/about", to: "welcome#about", as: "about"

  get "app/views/welcome/displayview", to: "welcome#displayview", as: "displayview"
  get "app/views/welcome/infoview", to: "welcome#infoview", as: "infoview"

  get "app/views/welcome/classsummary", to: "welcome#classsummary", as: "classsummary"

  get "app/views/welcome/matching", to:"welcome#matching", as: "matching"
  post "app/views/welcome/displayscores", to:"welcome#displayscores", as: "displayscores"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookitem.rb
class Bookitem < ApplicationRecord
  validates_presence_of :title, :author
  validates_uniqueness_of :title
  validates_numericality_of :pages,
    :message => "Should be numeric value."
  #belongs_to :users2book
end

app/models/dualbooklist.rb
class Dualbooklist < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/models/reward.rb
class Reward < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  #has_many :users2book
end

app/models/users2book.rb
class Users2book < ApplicationRecord
  #belongs_to :User
  #has_many :bookitem
end

app/models/users2goal.rb
class Users2goal < ApplicationRecord
end

app/models/users2reward.rb
class Users2reward < ApplicationRecord
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@goals = Goal.all
	end


	def show 
		@goal = Goal.find(params[:id])
	end


	def new
		@goal = Goal.new
	end


	def edit
		@goal = Goal.find(params[:id])		
	end


	def create
		@goal = Goal.new(goal_params)

		if @goal.save

			if false
				redirect_to @goal
			end
			redirect_to goals_path
		else
			render 'new'
		end
	end


	def update
  		@goal = Goal.find(params[:id])

  		if @goal.update(goal_params)
  			redirect_to @goal
  		else
  			render 'edit'
  		end
 

	end
	

	def destroy
		@goal = Goal.find(params[:id])
		@goal.destroy

		redirect_to goals_path
	end


	private
	def goal_params
		params.require(:goal).permit(:name,:text,:is_class)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	http_basic_authenticate_with name: "12", password: "12", only: :destroy
	def index
		@users = User.all
	end


	def show

		@users2books = Users2book.all
		@bookitems = Bookitem.all

		@user = User.find(params[:id])
		@newUserBook = Users2book.new

		@page_sum = 0
		@books_total = 0
			@booklist = Users2book.all.each do |user2book|
				if user2book.userid === @user.id
				 @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages
				 @books_total = @books_total + 1
				end
			end
		@user.pages_read = @page_sum
		@user.books_read = @books_total

		#this will implement the users reading level based on # of pages and books read
		@standing = ""
		if @user.pages_read >= 0 && @user.books_read >= 0
			@standing = "Novice"
		end
		if @user.pages_read > 200 && @user.books_read > 3
			@standing = "Apprentice"
		end
		if @user.pages_read > 1000 && @user.books_read > 10
			@standing = "Journey Man"
		end
		if @user.pages_read > 10000 && @user.books_read > 20
			@standing = "Master"
		end
		@user.reading_level = @standing
		@user.save
	end



	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
		@page_sum = 0
		@books_total = 0
			@booklist = Users2book.all.each do |user2book|
				if user2book.userid === @user.id
				 @page_sum = @page_sum + Bookitem.find_by_id(user2book.bookid).pages
				 @books_total = @books_total + 1
				end
			end
		@user.pages_read = @page_sum
		@user.books_read = @books_total

		#this will implement the users reading level based on # of pages and books read
		@standing = ""
		if @user.pages_read >= 0 && @user.books_read >= 0
			@standing = "Novice"
		end
		if @user.pages_read > 200 && @user.books_read > 3
			@standing = "Apprentice"
		end
		if @user.pages_read > 1000 && @user.books_read > 10
			@standing = "Journey Man"
		end
		if @user.pages_read > 10000 && @user.books_read > 20
			@standing = "Master"
		end


		@user.reading_level = @standing
		@user.save

	end


	def create

		@user = User.new(user_params)

		@user.pages_read = 0
		@user.books_read = 0

		@user.reading_level = "Novice"

		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end


	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end


private
	def user_params
		params.require(:user).permit(:name, :is_teacher, :age, :pages_read, :books_read, :reading_level, :book_list)

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookitems_helper.rb
module BookitemsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/users2books_helper.rb
module Users2booksHelper
end

app/helpers/users2goals_helper.rb
module Users2goalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 3.0 License
-->
<!DOCTYPE html>
<html>
  <head>
    <title>Readathon</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', :media => 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<meta name="keywords" content="" />
	<meta name="description" content="" />
    
  </head>




 <body>
<div id="wrapper">
		<div id="logo">
			<%= image_tag("sitelogo.png", class:"sitelogo",height: '64', width: '64') %>
			<div class="sitetitle">
			<h1><a href="#">Readathon</a></h1>
			<p>Competitive reading software.</p>
			</div>
		</div>
	<!--<div id="header">
	</div> -->
	<div id="menu">
		<ul>
			<li class="first"><%= link_to 'HOME', controller: 'welcome' %></li>
			<li><%= link_to 'LEADERBOARD', controller: 'leaderboard', action: 'index' %></li>
			<li><%= link_to 'MasterView', masterview_path %></li>
			<li><%= link_to 'Users', controller: 'users' %></li>
			<li><%= link_to 'THE USER TO BOOK Table', controller: 'users2books'%></li>
			<li><%= link_to 'CLASS SUMMARY', controller: 'welcome', action: 'classsummary' %></li>
		</ul>
	</div>
	<div id="page">
		<div id="content">
			
    		<%= yield %>


			<div style="clear: both;">&nbsp;</div>
		</div>
		<!-- end #content -->
		<div style="clear: both;">&nbsp;</div>
	</div>



<div id="footer">
	<p>
		<%= link_to 'Contact', contact_path %>
		<%= link_to 'about', about_path %>
	</p>
	<p>Copyright &copy; 2017 Team Avatar!</p>
</div>
</div>
</body>
</html>